included:
  - todo-app
  
excluded:
  - .github/*
  - fastlane/*
  - .swiftlint.yml
  - .gitignore.yml

disabled_rules:
  - trailing_whitespace
  - function_body_length
  - nesting
  - unused_optional_binding
  - line_length
  - colon
  - comma
  - void_return
  - statement_position
  - opening_brace
  - comment_spacing
  - mark
  - identifier_name
  - control_statement
  - unused_closure_parameter
  - unneeded_break_in_switch
  - redundant_optional_initialization
  - switch_case_alignment
  - cyclomatic_complexity
  - multiple_closures_with_trailing_closure
  - no_space_in_method_call
  - orphaned_doc_comment
  - empty_enum_arguments
  - type_name
  - file_length
  - todo
  - syntactic_sugar
  - redundant_string_enum_value
  - legacy_constructor
  - for_where
  - self_in_property_initialization
  - trailing_comma
  - trailing_semicolon
  - vertical_parameter_alignment
  - type_body_length
  - leading_whitespace
  - duplicate_imports
  - unused_capture_list
  - legacy_hashing
  - operator_whitespace
  - block_based_kvo
  - closure_parameter_position
  - function_parameter_count
  - shorthand_operator
  - superfluous_disable_command
  - _Null_unspecified
  - force_try

custom_rules:
  foundation_using:
    included: ".*.swift"
    regex: 'import Foundation'
    message: "Do you really need for Foundation ???"

  class_protocol:
    included: ".*.swift"
    regex: ': class'
    message: "Use Anyobject instead"

reporter:
  "xcode"

