
# Файл, где лежат функции с кейЧейном
import "KeyChain"

# Наша любимая дефолтная платформа
default_platform(:ios)


APPLE_KEY_ID = ENV["APPLE_KEY_ID"]

APPLE_ISSUER_ID = ENV["APPLE_ISSUER_ID"]

DEVELOPER_APP_ID = ENV["DEVELOPER_APP_ID"]

APPLE_KEY_CONTENT = ENV["APPLE_KEY_CONTENT"]

GIT_AUTHORIZATION = ENV["GIT_AUTHORIZATION"]

TEMP_KEYCHAIN_USER = ENV["TEMP_KEYCHAIN_USER"]

TEMP_KEYCHAIN_PASSWORD = ENV["TEMP_KEYCHAIN_PASSWORD"]

DEVELOPER_APP_IDENTIFIER = ENV["DEVELOPER_APP_IDENTIFIER"]

PROVISIONING_PROFILE_SPECIFIER = ENV["PROVISIONING_PROFILE_SPECIFIER"]

platform :ios do

  lane :clean do
    xcclean
    clear_derived_data
    clean_build_artifacts
  end
  
  lane :build do |scheme|
    environment = scheme[:environment]
    keychain_name = TEMP_KEYCHAIN_USER
    keychain_password = TEMP_KEYCHAIN_PASSWORD
    ensure_temp_keychain(keychain_name, keychain_password)

    api_key = app_store_connect_api_key(
      key_id: APPLE_KEY_ID,
      issuer_id: APPLE_ISSUER_ID,
      key_content: APPLE_KEY_CONTENT.gsub('\n', '\\n'),
      duration: 1200,
      in_house: false
    )
    
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "todo-app.xcodeproj"
    )

    match(
      type: 'appstore',
      app_identifier: "#{DEVELOPER_APP_IDENTIFIER}",
      git_basic_authorization: Base64.strict_encode64(GIT_AUTHORIZATION),
      readonly: true,
      keychain_name: keychain_name,
      keychain_password: keychain_password,
      api_key: api_key
    )

    gym(
      configuration: environment,
      project: "todo-app.xcodeproj",
      clean: true,
      scheme: "#{environment} todo-app",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
            DEVELOPER_APP_ID => PROVISIONING_PROFILE_SPECIFIER
        }
      }
    )

    upload_to_testflight(
      apple_id: "#{DEVELOPER_APP_ID}",
      app_identifier: "#{DEVELOPER_APP_IDENTIFIER}",
      skip_waiting_for_build_processing: true,
      skip_submission: true,
      distribute_external: false,
      notify_external_testers: false,
      ipa: "./todo-app.ipa"
    )

    delete_temp_keychain(keychain_name)
  end

end
