name: develop actions
on:
    push:
        branches:
        - 'develop'
        - 'release/**-alpha'
    pull_request:
        types: [closed]
        branches:
        - 'develop'
        - 'release/**-alpha'

env: default
jobs:
    prepare:
        name: Prepare
        runs-on: macOS-latest
        
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            
            - name: Cleaning the project
              uses: maierj/fastlane-action@v2.2.0
              with:
                lane: 'clean'
                
            - name: Linting the project
              uses: maierj/fastlane-action@v2.2.0
              with:
                lane: 'lint_code'

    building:
        name: Building
        needs: prepare
        runs-on: macOS-latest
        
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            
            - name: Building the project
              uses: maierj/fastlane-action@v2.2.0
              with:
                lane: 'build'
                options: '{ "environment": "test" }'

    testflight:
        name: Building
        needs: prepare
        runs-on: macOS-latest
        
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            
            - name: Deplying to testflight
              uses: maierj/fastlane-action@v2.2.0
              with:
                lane: 'deploy_to_tf'
                options: '{ "environment": "test" }'
