name: develop actions
on:
    pull_request:
        types: [closed]
        branches:
        - 'develop'
        - 'release/**-alpha'
jobs:
    prepare:
        name: Prepare
        runs-on: macOS-latest
        
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            
            - name: Cleaning the project
              uses: maierj/fastlane-action@v2.2.0
              with:
                lane: 'clean'
                
            - name: Linting the project
              uses: maierj/fastlane-action@v2.2.0
              with:
                lane: 'lint_code'
